version: 2

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/isaacaudet/aitop/cmd.Version={{.Version}}

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

brews:
  - repository:
      owner: isaacaudet
      name: homebrew-tap
    homepage: "https://github.com/isaacaudet/aitop"
    description: "Interactive terminal dashboard for Claude Code usage"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
